# Generated by Django 4.0.2 on 2022-04-06 12:18

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='categories/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(default='', max_length=200, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True)),
                ('emailId', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('username', models.CharField(default='', max_length=200, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(null=True, upload_to='profile_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=1000)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_user_info.user')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('price', models.IntegerField(default=1)),
                ('time_uploaded', models.DateTimeField(auto_now_add=True)),
                ('negotiation_status', models.BooleanField(default=False)),
                ('selling_reason', models.TextField(default='Used in last semester')),
                ('brand', models.CharField(default='', max_length=100)),
                ('time_used', models.CharField(default='1-1-1', max_length=100)),
                ('category_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product_user_info.category')),
                ('username', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product_user_info.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_user_info.product')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_user_info.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(default='')),
                ('read', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_user_info.user')),
            ],
        ),
        migrations.CreateModel(
            name='LikedProducts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_user_info.product')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_user_info.user')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_user_info.category')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_user_info.product')),
            ],
        ),
    ]
